### ISSUE TITLE
Pretrained Model?

### ISSUE THREAD

**Issue by shreyaskamathkm** [svip-lab/FastMVSNet#1]
Hi,

Could you please provide a pre-trained model? It would be very helpful.

Thank you,
Best,
Shreyas

**Comment by niujinshuchong** [comment]
@shreyaskamathkm 

The model can be found under https://github.com/svip-lab/FastMVSNet/tree/master/outputs.

**Comment by shreyaskamathkm** [comment]
Thank you so much!
