### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by jackyangs** [svip-lab/FastMVSNet#10]
I'm sorry to bother you for your time. I would like to know how to calculate the accuracy rate.

**Comment by niujinshuchong** [comment]
@jackyangs 
We use the matlab scripts from DTU dataset to calculate the metric.

**Comment by jackyangs** [comment]
I downloaded it, but I don't know which one to use.

**Comment by lilipopololo** [comment]
@jackyangs can you calculate the accuracy rate by using that matlab script?

**Comment by niujinshuchong** [comment]
@lilipopololo 
After downloading the matlab script. You need to change 3 *.m files as follows.
1. GetUsedSets.m 
    UsedSets=[1 4 9 10 11 12 13 15 23 24 29 32 33 34 48 49 62 75 77 110 114 118];
2. getPaths.m
    change the path to where you put your data. You can put the fused point cloud in Points/fastmvsnet
3. BaseEvalMain_web.m 
    set method_string='fastmvsnet';

Then simply run BaseEvalMain_web.m.

Note that the *.ply files should be named like fastmvsnet001_l3.ply.

**Comment by lilipopololo** [comment]
thank you very much. @niujinshuchong
