### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by zhao-you-fei** [svip-lab/FastMVSNet#18]
Traceback (most recent call last):
  File "E:\桌面\test\FastMVSNet\fastmvsnet\train.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

python版本和对应的pytorch版本是什么啊

**Comment by niujinshuchong** [comment]
@zhao-you-fei 

python 3.6.9
pytorch 1.2.0

不过其他版本也可以。
