### ISSUE TITLE
Depth Fusion

### ISSUE THREAD

**Issue by huanghailiang** [svip-lab/FastMVSNet#3]
Hi,
    I use your guide “ python tools/depthfusion.py -f dtu -n flow2 ” ，but I got an empty folder，can't get the file of "ply".
   Can you give me some guide? Thanks!!

**Comment by niujinshuchong** [comment]
@huanghailiang 

Maybe you could try "python tools/depthfusion.py -f dtu -n flow2 --eval_folder data/dtu2/Eval --fusibile_exe_path /root/projects/fusibile/fusibile".

Make sure you have installed fusibile.

**Comment by huanghailiang** [comment]
> @黄海亮
> 
> 也许您可以尝试“ python tools / depthfusion.py -f dtu -n flow2 --eval_folder data / dtu2 / Eval --fusibile_exe_path / root / projects / fusibile / fusibile”。
> 
> 确保已安装易熔品。

First of all, thank you for your reply.

**Comment by huanghailiang** [comment]
> @黄海亮
> 
> 也许您可以尝试“ python tools / depthfusion.py -f dtu -n flow2 --eval_folder data / dtu2 / Eval --fusibile_exe_path / root / projects / fusibile / fusibile”。
> 
> 确保已安装易熔品。

First of all, thank you for your reply.

**Comment by huanghailiang** [comment]
> @huanghailiang
> 
> Maybe you could try "python tools/depthfusion.py -f dtu -n flow2 --eval_folder data/dtu2/Eval --fusibile_exe_path /root/projects/fusibile/fusibile".
> 
> Make sure you have installed fusibile.

Thanks!

**Comment by Todd-Qi** [comment]
你好，请教一个问题。
为什么在prob_map上采样的时候采用`LANCZOS4`方式呢？是有什么讲究吗？
